
name: Package Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    if: ${{ github.event.action == 'published' && !github.event.release.draft}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@spydersoft'
      - name: Get Version from Release Tag
        run:  TAG=$(git describe --tags); echo "VERSION=${TAG}${RELEASE}" >> $GITHUB_ENV
      - run: |
          yarn install
          yarn ci
        name: Run Build (with tests)
      - name: Change Version in package.json
        shell: pwsh
        run: |
          $packageJson = Get-Content -Raw -Path package.json | ConvertFrom-Json
          $packageJson.version = ${{ env.VERSION }}
          $packageJson | ConvertTo-Json -Depth 100 | Set-Content -Path package.json
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}